### ISSUE TITLE
Installation for `pyPostal==1.1` failed (from PyPI)

### ISSUE THREAD

**Issue by philippeowagner** [openvenues/pypostal#11]
`IOError: [Errno 2] No such file or directory: 'README.rst'`

**Comment by philippeowagner** [comment]
Ouups.

**Comment by barraponto** [comment]
I see the same error.

**Comment by thatdatabaseguy** [comment]
The name pypostal was taken by another library on PyPI. Aside from the repo name, this package is simply named "postal" and can be installed with ```pip install postal```
