### ISSUE TITLE
Errors on installation - Debian 8.6 VM

### ISSUE THREAD

**Issue by dndln** [openvenues/pypostal#12]
What I did:
(installed in ~/Documents/libpostal)

```
git clone https://github.com/openvenues/libpostal
cd libpostal
./bootstrap.sh
./configure LDFLAGS=-L/usr/lib64 --datadir=$(pwd)/data --prefix=$(realpath $(pwd)) --bindir=$(realpath $(pwd)/bin)
sudo make install
./src/address_parser
```
```
Loading models...
ERR Error loading transliteration module, LIBPOSTAL_DATA_DIR=/home/user/Documents/libpostal/data/libpostal
at libpostal_setup (libpostal.c:1069) errno: No such file or directory
```
libpostal/data is only 29.2kb big, but I have 24.3GB of free space.

libpostal/data/libpostal only has last_updated, last_updated_geo, last_updated_language_classifier, and last_updated_parser, and they all only have `Jan 1 00:00:00 1970'.

**Comment by thatdatabaseguy** [comment]
The data files didn't download correctly. There should be ~2.2G of space in the datadir.

Try running ```make``` again and look for any errors. Or can run ```./src/libpostal_data download all $(pwd)/data``` to test downloading the data files directly.

**Comment by dndln** [comment]
okay, turns out I'm dumb and curl wasn't installed. Thanks!
