### ISSUE TITLE
Error loading transliteration module

### ISSUE THREAD

**Issue by paulds8** [openvenues/pypostal#15]
Good day

I have installed libpostal and can successfully run address_parser

```
root@ubuntu:/home/pdossantos/libpostal# ./src/address_parser
Loading models...

Welcome to libpostal's address parser.

Type in any address to parse and print the result.

Special commands:
.exit to quit the program

> 6 Pringle St, Boksburg

Result:

{
  "house_number": "6",
  "road": "pringle st",
  "city": "boksburg"
}

>
```

However, when trying to use the Python bindings I get the following:

```
root@ubuntu:/home/pdossantos/tests# python test.py
ERR   Error loading transliteration module, dir=(null)
   at libpostal_setup_datadir (libpostal.c:1057) errno: No such file or directory
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from postal.parser import parse_address
  File "/usr/local/lib/python2.7/dist-packages/postal/parser.py", line 2, in <module>
    from postal import _parser
TypeError: Error loading libpostal data
```

Is there something additional that needs to be configured? I don't really understand why the dir is coming back as null.

**Comment by thatdatabaseguy** [comment]
Did you install the Python binding after installing libpostal, using all the steps in the README, and are both libpostal and pypostal version 1.0? Was this an upgrade from 0.3? Is libpostal installed in a custom directory? Note that on Ubuntu, you may need to run ```sudo ldconfig``` before installing the Python bindings.

**Comment by paulds8** [comment]
Yes, the bindings were installed afterwards following the README. This was not an upgrade. Libpostal is installed in my home directory.

Will try a reinstall and provide feedback.

**Comment by cgreening** [comment]
I had the same issue on the mac - when I ran configure the first time I accidently included single quotes around the datadir which broken things:

```
./configure --datadir='/Users/chrisgreening/Work/fuzzy_matching/data'
```

Should have been

```
./configure --datadir=/Users/chrisgreening/Work/fuzzy_matching/data
```
