### ISSUE TITLE
configure datadir don't accept path

### ISSUE THREAD

**Issue by oxidworks** [openvenues/pypostal#18]
Hello, I try to configure pypostal and for that I have to set datadir:

> ./configure --datadir=[...some dir with a few GB of space...]

but I get the error message:
```
 ./configure --datadir=["/opt/libpostal/"]
configure: error: expected an absolute directory name for --datadir: [/opt/libpostal/]
```
But I don't understand, /opt/libpostal/ is an absolute directory name ...

**Comment by thatdatabaseguy** [comment]
Oh, without the square brackets. They're just used in the shell instructions to denote "your data dir goes here".

**Comment by oxidworks** [comment]
Thank you for your aswer, I will try this next time.
