### ISSUE TITLE
Cannot Install pip install postal in windows

### ISSUE THREAD

**Issue by ibrahim-appgodz** [openvenues/pypostal#19]
**# Also installed Visual C++ compiler for python**

E:\Desktop>pip install postal
Collecting postal
  Using cached postal-1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from postal)
Building wheels for collected packages: postal
  Running setup.py bdist_wheel for postal ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\ibrahim\\appdata\\local\\temp\\pip-build-x33nju\\postal\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\ibrahim\appdata\local\temp\tmpyovm4wpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\postal
  copying postal\expand.py -> build\lib.win-amd64-2.7\postal
  copying postal\parser.py -> build\lib.win-amd64-2.7\postal
  copying postal\__init__.py -> build\lib.win-amd64-2.7\postal
  creating build\lib.win-amd64-2.7\postal\tests
  copying postal\tests\test_expand.py -> build\lib.win-amd64-2.7\postal\tests
  copying postal\tests\test_parser.py -> build\lib.win-amd64-2.7\postal\tests
  copying postal\tests\__init__.py -> build\lib.win-amd64-2.7\postal\tests
  creating build\lib.win-amd64-2.7\postal\utils
  copying postal\utils\encoding.py -> build\lib.win-amd64-2.7\postal\utils
  copying postal\utils\enum.py -> build\lib.win-amd64-2.7\postal\utils
  copying postal\utils\omitted.py -> build\lib.win-amd64-2.7\postal\utils
  copying postal\utils\__init__.py -> build\lib.win-amd64-2.7\postal\utils
  running build_ext
  building 'postal._expand' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\postal
  C:\Users\Ibrahim\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/local/include -Ic:\python27\include -Ic:\python27\PC /Tcpostal/pyexpand.c /Fobuild\temp.win-amd64-2.7\Release\postal/pyexpand.obj -std=c99 -Wno-unused-function
  cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'
  error: command 'C:\\Users\\Ibrahim\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for postal
  Running setup.py clean for postal
Failed to build postal
Installing collected packages: postal
  Running setup.py install for postal ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\ibrahim\\appdata\\local\\temp\\pip-build-x33nju\\postal\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\ibrahim\appdata\local\temp\pip-xlfvwe-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\postal
    copying postal\expand.py -> build\lib.win-amd64-2.7\postal
    copying postal\parser.py -> build\lib.win-amd64-2.7\postal
    copying postal\__init__.py -> build\lib.win-amd64-2.7\postal
    creating build\lib.win-amd64-2.7\postal\tests
    copying postal\tests\test_expand.py -> build\lib.win-amd64-2.7\postal\tests
    copying postal\tests\test_parser.py -> build\lib.win-amd64-2.7\postal\tests
    copying postal\tests\__init__.py -> build\lib.win-amd64-2.7\postal\tests
    creating build\lib.win-amd64-2.7\postal\utils
    copying postal\utils\encoding.py -> build\lib.win-amd64-2.7\postal\utils
    copying postal\utils\enum.py -> build\lib.win-amd64-2.7\postal\utils
    copying postal\utils\omitted.py -> build\lib.win-amd64-2.7\postal\utils
    copying postal\utils\__init__.py -> build\lib.win-amd64-2.7\postal\utils
    running build_ext
    building 'postal._expand' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\postal
    C:\Users\Ibrahim\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/local/include -Ic:\python27\include -Ic:\python27\PC /Tcpostal/pyexpand.c /Fobuild\temp.win-amd64-2.7\Release\postal/pyexpand.obj -std=c99 -Wno-unused-function
    cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'
    error: command 'C:\\Users\\Ibrahim\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\ibrahim\\appdata\\local\\temp\\pip-build-x33nju\\postal\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\ibrahim\appdata\local\temp\pip-xlfvwe-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\ibrahim\appdata\local\temp\pip-build-x33nju\postal\

**Comment by thatdatabaseguy** [comment]
Hi Mohamed,

The libpostal C library does not currently support Windows, and there are no current plans to support it, but I will accept patches. Several users have said they are going to implement this but I have not yet seen a pull request.

At the moment you will have to compile it in a Linux VM to use it.

./al

**Comment by ibrahim-appgodz** [comment]
Dear,

 

Thank you for your kind reply.

 

I will try to have it in my Linux machine.

 

Thanks for your support.

 

 

Kind Regards,

Mohamed Ibrahim N

**Comment by hamsabharathi** [comment]
![image](https://user-images.githubusercontent.com/24528668/40357406-bacd5b50-5dd9-11e8-804b-9704ece94b9c.png)

Not able to pip install
