### ISSUE TITLE
SystemError: initialization of _parser raised unreported exception

### ISSUE THREAD

**Issue by hongrongz** [openvenues/pypostal#21]
I am having issue with the parser module. Detail error info below:
Expand module works fine.

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-11-4380c3410a3a> in <module>()
----> 1 from postal.parser import parse_address

/Users/zhanghuiting/anaconda/lib/python3.6/site-packages/postal/parser.py in <module>()
      1 """Python bindings to libpostal parse_address."""
----> 2 from postal import _parser
      3 from postal.utils.encoding import safe_decode
      4 
      5 

SystemError: initialization of _parser raised unreported exception

And I just tested the address_parser and shows the below error:

ERR   Could not find parser model file of known type
   at address_parser_load (address_parser.c:208) errno: No such file or directory

Thank you in advance.

Nick

**Comment by thatdatabaseguy** [comment]
Hi @hongrongz, that sounds like libpostal's data files were not downloaded. Make sure that [libpostal](https://github.com/openvenues/libpostal) has built successfully first and that you can use the address_parser client. During the `configure` step, set `--datadir` to a directory that has at least 1.8G of free space to house the current models. Also make sure `curl` is installed, that's been an issue before. The last stage of `make`will download the files and you should see 1.8G (the size of the current models in 1.0, may change in subsequent runs) in the selected data directory.

**Comment by HARIHARAN1103** [comment]
I to have the same issue. I was not able see _parser python file. I have all 7 python files that you have included in the pypostal/postal/ ( dedupe.py, expand.py, near_dupe. py,normalize.py, parser.py, token_types.py, tokenize.py)
![Screenshot from 2020-01-09 18-54-32](https://user-images.githubusercontent.com/35688511/72071312-83633900-3311-11ea-8ffe-c21fca888ebc.png)
What is the solution. If you have that file means post that.
