### ISSUE TITLE
Release the GIL

### ISSUE THREAD

**Issue by thedrow** [openvenues/pypostal#3]
There are opportunities for parallelism in C extensions when no Python object is being used in a segment of the C extension.
There are such cases in pypostal.
See https://github.com/openvenues/pypostal/blob/master/postal/pyexpand.c#L200 until https://github.com/openvenues/pypostal/blob/master/postal/pyexpand.c#L208
and  https://github.com/openvenues/pypostal/blob/master/postal/pyparser.c#L143 until https://github.com/openvenues/pypostal/blob/master/postal/pyparser.c#L147

**Comment by thatdatabaseguy** [comment]
The underlying C library, libpostal, is not thread-safe, so releasing the GIL and allowing threads will almost certainly have unintended consequences.

Libpostal is quite fast - as in process every address in OpenStreetMap in just over an hour on a single core fast. IMHO it's premature optimization to worry about multithreading unless there's a concrete use case where greater throughput is needed _within_ a single process (it's totally fine to use multiple shared-nothing processes, MapReduce, etc. on multicore machines).

**Comment by thedrow** [comment]
If libpostal is not thread safe you're right. Releasing the GIL is a bad idea.
The purpose of releasing the GIL is to allow higher throughput in applications. Not necessarily parallelising calls to libpostal itself.
In any case I'll take the issue upstream and we'll see if there's anything to be done in order to make libpostal thread safe.
