### ISSUE TITLE
pip installer looks for README.rst, whereas it's README.md

### ISSUE THREAD

**Issue by Prooffreader** [openvenues/pypostal#32]
Trying to install in Anaconda Python 3.6 on Ubuntu 16.10:

pip install pypostal
Collecting pypostal
  Downloading pyPostal-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-it1zbgs0/pypostal/setup.py", line 10, in <module>
        long_description=codecs.open('README.rst', "r", "utf-8").read(),
      File "/home/david/anaconda3/envs/py36/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-it1zbgs0/pypostal/

**Comment by Prooffreader** [comment]
This seems to be a pypi issue, as it does not have 1.1.6 as in this repo.

The following worked:
git clone https://github.com/openvenues/pypostal.git
cd pypostal
python setup.py install

**Comment by albarrentine** [comment]
Ah, it's `pip install postal` not pypostal. The name pypostal was already taken.

**Comment by Prooffreader** [comment]
Should have read the README better!

**Comment by zhenghy** [comment]
add `include README.md` to file `MANIFEST.in`.
if file no exist , create it.
