### ISSUE TITLE
Need an option to set the data-dir in python

### ISSUE THREAD

**Issue by uzadude** [openvenues/pypostal#58]
Hi,
We have the same requirement mentioned [here](https://github.com/openvenues/libpostal/issues/153), but in pypostal instead of jpostal.
We tracked down the python call to [here](https://github.com/openvenues/pypostal/blob/60641c1c1d7a575b5655774813927db00e089a05/postal/pyexpand.c#L230), but not sure how would you suggest to init the expand object with `datadir` param.
could you please take a look?

**Comment by uzadude** [comment]
Currently we have patched the code this way: #59, and it works on our Spark cluster.
steps to run in PySpark (take off from [here](https://github.com/openvenues/libpostal/issues/153#issuecomment-274926309)):
1. build the libpostal 
2. put all .so files into a tar.gz (`tar -czf libpostal_sos.tar.gz .`)
3. put all data files into a tar.gz (`tar -czf libpostal_datadir.tar.gz .`)
4. build the patched pypostal (`python setup.py bdist_egg`)
5. run Spark with following configurations:
```
spark.yarn.dist.archives: libpostal_sos.tar.gz,libpostal_datadir.tar.gz
spark.jars/spark.files: postal-1.1.8-py3.7-linux-x86_64.egg
spark.executorEnv.LD_LIBRARY_PATH: "./libpostal_sos.tar.gz/lib"
spark.executorEnv.LIBPOSTAL_DATA_DIR: "./libpostal_datadir.tar.gz"
spark.executorEnv.PYTHON_EGG_CACHE: "./.cache"
spark.yarn.appMasterEnv.LD_LIBRARY_PATH: "./libpostal_sos.tar.gz/lib"
spark.yarn.appMasterEnv.LIBPOSTAL_DATA_DIR: "./libpostal_datadir.tar.gz"
spark.yarn.appMasterEnv.PYTHON_EGG_CACHE: "./.cache"
```

**Comment by jonathaneschbach** [comment]
@uzadude  I did step 1. could you please explain more in detail what you are meaning by points 2 and 3? Where do I find the .so and "data" files?

**Comment by uzadude** [comment]
Hi sure, I can try.. hope it didn't change a lot from 3 years ago.

2. after building the libpostal from source, there should be ".so" file(s) somewhere in the build folder (just do `find . -name '*.so'`).
so add them to a tag.gz.

3. also, when you built you have given some folder as `--datadir=...`. so do the same for the content of this folder.

* note - you should have built everything on the same env like the executors that will run the code, so the easiest way is to use Docker for that.

**Comment by jonathaneschbach** [comment]
@uzadude Thanks a lot for your feedback. When executing a udf with libpostal on a spark dataframe I receive 
AttributeError: module 'postal._parser' has no attribute 'parse_address'
It seems that the python egg is there and the library is loaded but something seems to be missing.
Do you have an idea about this?
Any help is welcome!
