### ISSUE TITLE
near_dupe_hashes returns empty array

### ISSUE THREAD

**Issue by mhmdmodan** [openvenues/pypostal#60]
Not sure what's going on, postal.near_dupe.near_dupe_hashes simply returns an empty list no matter what the inputs are. I'm passing in the labels and values created from the parse_address function

**Comment by InnovativeInventor** [comment]
I can reproduce this.

**Comment by nitindatta** [comment]
Hi is there any workaround or fix that can be shared.

**Comment by mhmdmodan** [comment]
@nitindatta so I decided to dig into this a little bit. I _think_ actually that near_dupe_hashes is working as intended. If you use the libpostal example address which contains both a name and address of `The Book Club 100-106 Leonard St, Shoreditch, London, Greater London, EC2A 4RH, United Kingdom` then near_dupe_hashes does output hashes. However, if you try just an address like "2655 Colfax Ave S, Apt 650, Minneapolis, MN 55408" then you get an empty array.

I think I figured out why. Take a look at the `near_dupe_hashes` documentation [here](https://github.com/openvenues/pypostal/blob/master/postal/near_dupe.py), key thing are the options. Note the last 3 options: `name_and_address_keys`, `name_only_keys`, `address_only_keys`. Now take a look at the defaults for these options [here](https://github.com/openvenues/libpostal/blob/0327150d2b0363c7d8c7a5a37ad8ea7b4a65806a/src/libpostal.c#L68). We see the following:

`name_and_address_keys = True`
`name_only_keys = False`
`address_only_keys = False`

So we see that, by default, in order to generate hashes, our input address must have a name field. To resolve the address only case (like my nonworking example above), you must additionally pass in `address_only_keys=True`. You can also pass in `name_only_keys=True` if you want to generate hashes for addresses which only contain a name. Personally, from a typical entity resolution standpoint, I would be already matching entities on name entirely separately from address matching with libpostal, therefore I would do True, False, True, respectively.

Here's some example code:

```python
from postal.parser import parse_address
from postal.near_dupe import near_dupe_hashes

def near_dupe_wrapper(address, **kwargs):
    parsed = dict(parse_address(address))
    return near_dupe_hashes(list(parsed.values()), list(parsed.keys()), **kwargs)

# works with default options
print(near_dupe_wrapper('John Smith, 2655 Colfax Ave S, Apt 650, Minneapolis, MN 55408'))

# this one doesn't have a name so it will fail by default
print(near_dupe_wrapper('2655 Colfax Ave S, Apt 650, Minneapolis, MN 55408'))

# to make it work, we must pass in address_only_keys=True
# so our options will end up being:
# name_and_address_keys = True
# name_only_keys = False
# address_only_keys = True <-this was changed
print(near_dupe_wrapper('2655 Colfax Ave S, Apt 650, Minneapolis, MN 55408', address_only_keys=True))
```

**Comment by mhmdmodan** [comment]
Duplicate of #49

**Comment by hydeta** [comment]
@mhmdmodan thanks for that response it was very helpful.  One thing I'm struggling to understand is if my input is `'28 liberty street new york new york 10005'` then the output I get from the near_dupe_hashes is ```['act|liberty street|28|new york',
 'act|liberty|28|new york',
 'apc|liberty street|28|10005',
 'apc|liberty|28|10005']```
 
 
How are these values meant to be interpreted and used?  They look nothing like traditional hashes that I'm used to.

**Comment by mhmdmodan** [comment]
@hydeta  Hi, it's been a really long time since I've used this module, and I no longer have access to the code I wrote with it.

IIRC you would store all of those hashes for your known address in a set. This is your "known" set. Then when you get a new "near" address like `28 liberty street 10005`, you would also run this through the near dupes hash function and you would get something like:

```python
[ 'apc|liberty street|28|10005',
 'apc|liberty|28|10005']
```

This is your new set. In order to see if this new address is the same as the known address (or, close enough), you would see if either of the two items in your new set are in your known set. If true, it's a near match.

Basically the way near dupes hash works is that it generates every permutation for your address in a standardized format that provides the minimum information possible to recreate the address.

Notice how for the known set you have 4 but the new set only has 2. That's because the new address has less information so the near dupes hash function can't pull out "new York", but for the known address it knew that you only need zip or state, not both.

Imagine the known and new addresses were swapped. Your known set would only have 2 entries with no state info, just zip. Now imagine the new addresse enters your system and matches the old address, there's actually more information now and you can update the known address with the new set entries in case a 3rd address enters the system with state but no zip.
