### ISSUE TITLE
Can't pass country to parse_address 

### ISSUE THREAD

**Issue by jonakirke94** [openvenues/pypostal#61]
It appears I'm not able to pass in a country-code:

`addr_zagat_parse = [parse_address(addr, country='us') for addr in matched_address.addr_zagat]`

Gives the error:

`---> 15 return _parser.parse_address(address, language=language, country=country)`
`TypeError: Parameter must be bytes or unicode`

I also posted an issue in the original c library, wasn't sure where to post it!

**Comment by cipri-tom** [comment]
I'm also having this problem

**Comment by cipri-tom** [comment]
Note that even if my PR is accepted, it won't change anything because the flag is not used yet in the C library. See my comment to your issue there: https://github.com/openvenues/libpostal/issues/497
