### ISSUE TITLE
Installation/Usage unclear

### ISSUE THREAD

**Issue by easherma** [openvenues/pypostal#8]
Hi there. Running in terminal on a CentOS7 box. I installed libpostal and can use its utilities, and followed instructions to install python bindings (sudo pip install postal), but I get this error when trying to use code examples:

>from postal.expand import expand_address ...
>cannot open shared object file: No such file or directory...

dir(postal) = ['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']

**Comment by thatdatabaseguy** [comment]
That sounds import path related. Did you just run pip install, or did you clone the repo first? If you cloned the repo, ran pip install, then try to import from the same checkout directory, Python's going to try to import first from the local package rather than the installed version in site-packages (and the local package hasn't compiled the C libs, so it will error). If that's what happened, you can still import from your local checkout by running ```python setup.py build_ext --inplace```.

If that's not it, it may be related to the use of sudo.  I haven't used CentOS in a few years, so my information is slightly out of date, but as I recall CentOS has been slow to adopt newer Python versions, which often created conflicts between system python and the version used by applications. If that's still the case, you might try creating a virtualenv, activating and then doing a sudo-less ```pip install postal```.

**Comment by easherma** [comment]
`pip install` didn't work for me initially, so I tried cloning the repo. In the end, I've followed both instructions (pip install as well as building the extensions in place in my cloned directory), and both operations worked, but I still am having the issue. 

If I wanted to chuck this and start over, is it as simple as deleting my locally installed repo or do I need to 'uninstall' it somehow?

**Comment by thatdatabaseguy** [comment]
```pip uninstall postal```/```pip install postal``` should work. Might want to do the uninstall with and without sudo as well. Could be a permissions issue.

What happened with the initial ```pip install```?

**Comment by easherma** [comment]
Should that work irregardless of the pypostal clone + python setup.py build_ext --inplace I did? I tried the uninstall/install and have the same problem as before. 

Looking back at my log, I believe this was my initial attempt to install postal:

> sudo pip install postal
Collecting postal
  Downloading postal-0.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from postal)
Installing collected packages: postal
  Running setup.py install for postal ... [?25l- error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8gi9dn/postal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-spCWhV-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/postal
    copying postal/__init__.py -> build/lib.linux-x86_64-2.7/postal
    copying postal/expand.py -> build/lib.linux-x86_64-2.7/postal
    copying postal/parser.py -> build/lib.linux-x86_64-2.7/postal
    creating build/lib.linux-x86_64-2.7/postal/tests
    copying postal/tests/__init__.py -> build/lib.linux-x86_64-2.7/postal/tests
    copying postal/tests/test_expand.py -> build/lib.linux-x86_64-2.7/postal/tests
    copying postal/tests/test_parser.py -> build/lib.linux-x86_64-2.7/postal/tests
    creating build/lib.linux-x86_64-2.7/postal/utils
    copying postal/utils/__init__.py -> build/lib.linux-x86_64-2.7/postal/utils
    copying postal/utils/encoding.py -> build/lib.linux-x86_64-2.7/postal/utils
    copying postal/utils/enum.py -> build/lib.linux-x86_64-2.7/postal/utils
    copying postal/utils/omitted.py -> build/lib.linux-x86_64-2.7/postal/utils
    running build_ext
    building 'postal._expand' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/postal
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/include -I/usr/include/python2.7 -c postal/pyexpand.c -o build/temp.linux-x86_64-2.7/postal/pyexpand.o -std=c99 -Wno-unused-function
    postal/pyexpand.c:1:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
> 
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8gi9dn/postal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-spCWhV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8gi9dn/postal/

Seemed to be dependency issue, I think I was missing one of the tools you listed as required.

**Comment by thatdatabaseguy** [comment]
Ah, ok. Python.h can be obtained using ```yum install python-devel``` I believe (or python27-devel, something like that).

```python setup.py build_ext --inplace``` would be run from the pypostal directory (only really necessary if running a shell from that checkout directory for import path reasons).

**Comment by easherma** [comment]
Yeah, I figured that out which was able to resolve the pip install issue. Just put in some edits to the Readme to that effect to. 

So I'm not sure where to go from here, then. I can uninstall/install postal successfully and I have libpostal installed.

**Comment by thatdatabaseguy** [comment]
Ok. I don't think it's a CentOS thing if the other libpostal utilities are working. Somewhere there's 

Is what you posted a full trace? What's the message after "cannot open shared object file: No such file or directory"?

Also, can you do ```import postal``` from a shell, and check that the location of ```postal.__file__``` is where you expect it to be? When you ```ls``` that directory, you should see the files "_expand.so" and "_parser.so" which are the shared object files in question.

**Comment by easherma** [comment]
![help](https://cloud.githubusercontent.com/assets/10539855/16314924/b75f79d6-3945-11e6-9017-9bbfdaa47481.PNG)

**Comment by thatdatabaseguy** [comment]
Ah, that's a linker issue, nothing wrong with install. Just make sure /usr/local/lib (or wherever you installed libpostal) is on LD_LIBRARY_PATH. Add ```export LD_LIBRARY_PATH=/usr/local/lib``` to your bashrc and open a new ssh terminal to make it persistent across sessions, probably a good idea anyway since many C libraries install there.

**Comment by easherma** [comment]
Phew, that seems to have done it!

**Comment by easherma** [comment]
I'll close this as it _seems_ to be a pretty individual problem.

**Comment by tbonza** [comment]
+1 Thanks @easherma!

**Comment by KamilMroczek** [comment]
Had the same issue and this soled it for me. thanks guys!

**Comment by sumdan** [comment]
On CentOS, I needed to explicitly tell `ldconfig` to look in `/usr/local/lib`

```
cat /etc/ld.so.conf.d/$USER.conf 
/usr/local/lib
```

If I did that and subsequently ran `ldconfig`, `/usr/local/lib/libpostal.so.1` was found

**Comment by Rkuro** [comment]
For anyone that still has issues with this, I had to do export LD_LIBRARY_PATH=/usr/local/lib64/ in order for the linker to find the correct file.  This was using centOS on AWS EC2 AMI. Hope this helps!

**Comment by stevelacy** [comment]
Not trying to re-start a 1+ year old issue, but can we get https://github.com/openvenues/pypostal/issues/8#issuecomment-228144654 added to the readme? I could send a pr.
I needed to google the error to find this issue, and the comment that solved it.
